### ISSUE TITLE
Improve list page table

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#172]
- [x] alter row background color
- [x] colomns sort
- [x] responsive view (colomns drop ?)
- [x] better detail button/link
- [x] pagination frontend side
- [x] text filter

Legacy version https://carte.seignanx.com/content/liste/

**Comment by wazolab** [comment]
@frodrigo : What do you think about using [Vuetify's DataTable](https://vuetifyjs.com/en/components/data-tables/basics/#usage) ?
It includes:
- [Search](https://vuetifyjs.com/en/components/data-tables/data-and-display/#search)
- [Column Sorting](https://vuetifyjs.com/en/components/data-tables/data-and-display/#sorting-examples)
- [Pagination](https://vuetifyjs.com/en/components/data-tables/data-and-display/#pagination-examples)

About details button, what about just having a link on the `name` column instead of having a dedicated `details` column ?

What do you mean about "reactive view" ?

**Comment by frodrigo** [comment]
> @frodrigo : What do you think about using [Vuetify's DataTable](https://vuetifyjs.com/en/components/data-tables/basics/#usage) ? It includes:
> 
>     * [Search](https://vuetifyjs.com/en/components/data-tables/data-and-display/#search)
> 
>     * [Column Sorting](https://vuetifyjs.com/en/components/data-tables/data-and-display/#sorting-examples)
> 
>     * [Pagination](https://vuetifyjs.com/en/components/data-tables/data-and-display/#pagination-examples)

Yes.

> About details button, what about just having a link on the `name` column instead of having a dedicated `details` column ?

All columns are configurable and optional. We cannot make that.

> What do you mean about "reactive view" ?

Small screen, mobile view.

**Comment by wazolab** [comment]
Alright thanks for your answers.
So for the details we are expecting to have a UI button instead of just a Link ?
