### ISSUE TITLE
Filter categories of Embded Map and Embeded List

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#173]
Add URL parameter to filter category/menuitem by ids on `/embedded/` and `/embedded/category/{id}`.

- If filter contains only a single Category id, we don't display the CategorySelector
- If filter contains a MenuItem id, we show all Categories of the MenuItem
- By default include all the MenuItems (should already be the case)

**Comment by wazolab** [comment]
Just to be sure about the expected behavior and URLs:

**If filter contains only a single Category id, we don't display the CategorySelector**
This is the default case I think. We then have to hide CategorySelector if the Category have no children right ?

URL: `/embedded/category/{id}` | `/embedded/{id}/`

---
**If filter contains a MenuItem id, we show all Categories of the MenuItem**
Here we have a parent category ID so we want to constraint CategorySelector with only children categories options ?
It looks more convenient to set CategorySelector pre-selected on first child ? Then, user we switch between children categories ?

So I though about this URL:  `/embedded/category/{parentId}/{id}` | `/embedded/{parentId}/{id}`

---
**By default include all the MenuItems (should already be the case)**
It's not exactly the case for the moment as we are displaying a precise Category ID for the moment (with all MenuItems available in CategorySelector).
So should we be able to display an empty table until user selects something in CategorySelector ?

Suggested URL:  `/embedded/category` | `/embedded`

**Comment by wazolab** [comment]
@frodrigo : What do you think about dividing this issue in 2 PRs ? One for the List, the other for the Map. As the changes to be made will be on different places ...

**Comment by frodrigo** [comment]
ok.

> It looks more convenient to set CategorySelector pre-selected on first child ? Then, user will switch between children categories ?

No preset.

For the list the URL does not allow it. Maybe we must change the URL before. To `/category/embedded/{id}/` ? and support `/category/embedded/`.

**Comment by wazolab** [comment]
About `/category/embedded` we are expecting to have an un-preseted CategorySelector with an empty Table on first instance right ?
Then the user selects a category and is redirected to `/category/embedded/{id}` ?

**Comment by frodrigo** [comment]
> About /category/embedded we are expecting to have an un-preseted CategorySelector with an empty Table on first instance right ?
Then the user selects a category and is redirected to /category/embedded/{id} ?

Yes. Let's do this to be homogeneous with the map. Maybe a first PR with that.

**Comment by frodrigo** [comment]
> > About /category/embedded we are expecting to have an un-preseted CategorySelector with an empty Table on first instance right ?
> > Then the user selects a category and is redirected to /category/embedded/{id} ?
> 
> Yes. Let's do this to be homogeneous with the map. Maybe a first PR with that.

Maybe update the current PR #202
